apiVersion: apps/v1
kind: Deployment
metadata:
  name: clone-deployment
spec:
  selector:
    matchLabels:
      app: clone
  replicas: 3
  template:
    metadata:
      labels:
        app: clone
    spec:
      containers:
      - name: app-cn
        image: $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 80



---
apiVersion: v1
kind: Service
metadata:
  name: clone-svc
spec:
  selector:
    app: clone
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
